numero_1 = int (input("Digite o primeiro numero inteiro: "))
numero_2 = int (input("Digite o segundo numero inteiro: "))
real = float (input("Digite o numero real: "))
print("O produto do dobro do primeiro com metade do segundo: ",(numero_1*2)*(numero_2/2))
print("A soma do triplo do primeiro com o terceiro: ",(numero_1*3)+real)
print("O terceiro elevado ao cubo: ",(real*real*real))